### PR TITLE
Added support for GUI applications

### PR DESCRIPTION
**Pull request by brenohildebrand**
I created a **docker-compose.yml** file in order to have a config file to run the container. The workflow I use after this change is:

```
$ docker compose build
$ docker compose up -d
$ docker attach <container-id> 
```

**NOTE**: change `<container-id>` for the actual id. You can see it using `docker ps`.

Now any GUI app run from the container will appear in the host. I tested it with **gimp** and **emacs**. For more info about why these changes work [see the reference I used](https://gursimarsm.medium.com/run-gui-applications-in-a-docker-container-ca625bad4638).

**UPDATE**:
- The **docker-compose.yml** was deleted.
- Some new flags must be passed when building and running the container. 
When building use:
`$ docker build --build-arg DISPLAY=${DISPLAY} --build-arg XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR} --tag my_ubuntu_image .`
When running use:
`$ docker run -it --mount type=bind,source=/tmp/.X11-unix,target=/tmp/.X11-unix --mount type=bind,source=${XDG_RUNTIME_DIR},target=${XDG_RUNTIME_DIR} --name my_ubuntu_container my_ubuntu_image`
- Both the command to run and the command to build are commented in the **execute_me.sh**.
- To run KCacheGrind you need to install it with `$ apt-get install kcachegrind`, export environment variables from dbus-launch using `$ export $(dbus-launch)` and finally run `$ kcachegrind`. If **dbus-launch** cannot be found, try to update/install **dbus-x11** with `$ apt-get install dbus-x11`.

### CODE REVIEW

**Comment by brenohildebrand** [comment]
I think this is now ready to be accepted.

**Comment by Vinni-Cedraz** [comment]
Hi Breno, thanks a lot for the contribution but we still have an issue to solve before merging:

Screenshot from 2023-07-16 09-38-36

**Comment by brenohildebrand** [comment]
Hmm... this is weird. I'll try to replicate.

**Comment by Vinni-Cedraz** [comment]
> Hmm... this is weird. I'll try to replicate.

I simply ran kcachegrind inside the container after installing it with apt-get install kcachegrind and also after installing it with apt install kcachegrind

**Comment by brenohildebrand** [comment]
Try `$ apt-get update && apt-get install kcachegrind`. Then install dbus-x11 with `$ apt-get install dbus-x11`. Then `$ export $(dbus-launch)`. Finally run `$ kcachegrind`.

**Pull request merged**
